# run from root directory of repository

configfile: "config/config.yaml"

module pypsa_eur:
    snakefile:
        "pypsa-eur/Snakefile"
    prefix: 
        "workflow/pypsa-eur"
    config: config

use rule * from pypsa_eur

run = config.get("run", {})
RDIR = run["name"] + "/" if run.get("name") else ""
RESULTS = "workflow/pypsa-eur/results/" + RDIR

rule run_models:
    input: RESULTS + "graphs/costs.pdf"
    default_target: True
