configfile: "../config/config.yaml"

# must be in sync with config.pypsaeursec.yaml
RDIR = config['results_dir'] + config['run']

localrules: all, report, clean

subworkflow pypsaeur:
    workdir: "subworkflows/pypsa-eur"
    snakefile: "subworkflows/pypsa-eur/Snakefile"
    configfile: "../config/config.pypsaeur.yaml"

subworkflow pypsaeursec:
    workdir: "subworkflows/pypsa-eur-sec"
    snakefile: "subworkflows/pypsa-eur-sec/Snakefile"
    configfile: "../config/config.pypsaeursec.yaml"

rule all:
    message: "Run entire analysis and compile report."
    input:
        "../report/report.pdf",

rule sector:
    input: pypsaeursec(RDIR + "/graphs/costs.pdf")

rule report:
    message: "Compile report."
    input:
        tex="../report/report.tex",
        bib="../report/references.bib"
    output: "../report/report.pdf"
    shell:
        """
        pdflatex {input.tex}
        bibtex {input.bib})
        pdflatex {input.tex}
        pdflatex {input.tex}
        """


rule dag:
     message: "Plot dependency graph of the workflow."
     output:
         dot="../resources/dag.dot",
         pdf="../resources/dag.pdf"
     shell:
         """
         snakemake --rulegraph > {output.dot}
         dot -Tpdf -o {output.pdf} {output.dot}
         """


rule clean:
    message: "Remove all build results but keep downloaded data."
    run:
         import shutil

         shutil.rmtree("../resources")
         shutil.rmtree("../results")
         print("Data downloaded to data/ has not been cleaned.")
