# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "20231025-zecm"
  shared_resources: false

remote:
  ssh: "zecm"
  path: "scratch/projects/import-benefits"

scenario:
  simpl:
  - ''
  ll:
  - vopt
  clusters:
  - 110
  opts:
  - ''
  sector_opts:
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp
  # subsets of carriers
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+H2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+CH4
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+NH3
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+FT
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+MeOH
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+St # products
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+H2+CH4+NH3+FT+MeOH  # molecules
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+H2+CH4+NH3+FT+MeOH+St  # molecules + products
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+CH4+NH3+FT+MeOH  # hydrogen derivatives
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+MeOH+FT # liquid carbonaceous fuels
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+CH4+FT+MeOH  # carbonaceous fuels
  # subsets of carriers (+10%)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+H21.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+CH41.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+NH31.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+FT1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+MeOH1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+St1.1 # products
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1  # molecules
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1  # molecules + products
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+CH41.1+NH31.1+FT1.1+MeOH1.1  # hydrogen derivatives
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+MeOH1.1+FT1.1 # liquid carbonaceous fuels
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+CH41.1+FT1.1+MeOH1.1  # carbonaceous fuels
  # subsets of carriers (-10%)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+H20.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+CH40.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+NH30.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+FT0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+MeOH0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+St0.9 # products
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9  # molecules
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9  # molecules + products
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+CH40.9+NH30.9+FT0.9+MeOH0.9  # hydrogen derivatives
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+MeOH0.9+FT0.9 # liquid carbonaceous fuels
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+CH40.9+FT0.9+MeOH0.9  # carbonaceous fuels
  # subsets of carriers (-20%)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+H20.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+CH40.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+NH30.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+FT0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+MeOH0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+St0.8 # products
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8  # molecules
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8  # molecules + products
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+CH40.8+NH30.8+FT0.8+MeOH0.8  # hydrogen derivatives
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+MeOH0.8+FT0.8 # liquid carbonaceous fuels
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+CH40.8+FT0.8+MeOH0.8  # carbonaceous fuels
  # lower/higher import costs of molecules
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC+H20.7+CH40.7+NH30.7+FT0.7+MeOH0.7+St0.7
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC+H20.6+CH40.6+NH30.6+FT0.6+MeOH0.6+St0.6
  # lower import costs of electricity
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC0.9+H2+CH4+NH3+FT+MeOH+St
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC0.8+H2+CH4+NH3+FT+MeOH+St
  # lower/higher import costs of carbonaceous fuels
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC+H2+CH41.2+NH3+FT1.2+MeOH1.2+St
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC+H2+CH41.1+NH3+FT1.1+MeOH1.1+St
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC+H2+CH40.9+NH3+FT0.9+MeOH0.9+St
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC+H2+CH40.8+NH3+FT0.8+MeOH0.8+St
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC+H2+CH40.7+NH3+FT0.7+MeOH0.7+St
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp+AC+H2+CH40.6+NH3+FT0.6+MeOH0.6+St
  # import volume sensitivity (all)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp10000
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp9000
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp8000
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp7000
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp6000
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp5000
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp4000
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp3000
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp2000
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1500
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1000
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp500
  # import volume sensitivity (AC)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp7000+AC
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp6000+AC
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp5000+AC
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp4000+AC
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp3000+AC
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp2000+AC
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1000+AC
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp500+AC
  # import volume sensitivity (H2)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp7000+H2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp6000+H2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp5000+H2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp4000+H2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp3000+H2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp2000+H2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1000+H2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp500+H2
  # import volume sensitivity (CH4)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp5000+CH4
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp4000+CH4
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp3000+CH4
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp2000+CH4
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1000+CH4
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp500+CH4
  # import volume sensitivity (FT+MeOH)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp3000+FT+MeOH
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp2000+FT+MeOH
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1000+FT+MeOH
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp500+FT+MeOH
  # import volume sensitivity (NH3)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1500+NH3
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1000+NH3
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp500+NH3
  # import volume sensitivity (chemicals & products)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp7000+H2+CH4+NH3+FT+MeOH+St
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp6000+H2+CH4+NH3+FT+MeOH+St
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp5000+H2+CH4+NH3+FT+MeOH+St
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp4000+H2+CH4+NH3+FT+MeOH+St
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp3000+H2+CH4+NH3+FT+MeOH+St
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp2000+H2+CH4+NH3+FT+MeOH+St
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1000+H2+CH4+NH3+FT+MeOH+St
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp500+H2+CH4+NH3+FT+MeOH+St
  # import volume sensitivity (120%, expensive chemicals)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp10000+AC+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp9000+AC+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp8000+AC+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp7000+AC+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp6000+AC+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp5000+AC+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp4000+AC+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp3000+AC+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp2000+AC+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1500+AC+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1000+AC+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp500+AC+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  # import volume sensitivity (110%, expensive chemicals)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp10000+AC+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp9000+AC+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp8000+AC+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp7000+AC+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp6000+AC+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp5000+AC+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp4000+AC+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp3000+AC+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp2000+AC+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1500+AC+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1000+AC+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp500+AC+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  # import volume sensitivity (90%, cheap chemicals)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp10000+AC+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp9000+AC+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp8000+AC+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp7000+AC+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp6000+AC+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp5000+AC+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp4000+AC+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp3000+AC+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp2000+AC+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1500+AC+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1000+AC+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp500+AC+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  # import volume sensitivity (80%, cheap chemicals)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp10000+AC+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp9000+AC+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp8000+AC+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp7000+AC+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp6000+AC+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp5000+AC+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp4000+AC+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp3000+AC+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp2000+AC+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1500+AC+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1000+AC+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp500+AC+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  # import volume sensitivity (70%, cheap chemicals)
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp10000+AC+H20.7+CH40.7+NH30.7+FT0.7+MeOH0.7+St0.7
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp9000+AC+H20.7+CH40.7+NH30.7+FT0.7+MeOH0.7+St0.7
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp8000+AC+H20.7+CH40.7+NH30.7+FT0.7+MeOH0.7+St0.7
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp7000+AC+H20.7+CH40.7+NH30.7+FT0.7+MeOH0.7+St0.7
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp6000+AC+H20.7+CH40.7+NH30.7+FT0.7+MeOH0.7+St0.7
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp5000+AC+H20.7+CH40.7+NH30.7+FT0.7+MeOH0.7+St0.7
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp4000+AC+H20.7+CH40.7+NH30.7+FT0.7+MeOH0.7+St0.7
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp3000+AC+H20.7+CH40.7+NH30.7+FT0.7+MeOH0.7+St0.7
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp2000+AC+H20.7+CH40.7+NH30.7+FT0.7+MeOH0.7+St0.7
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1500+AC+H20.7+CH40.7+NH30.7+FT0.7+MeOH0.7+St0.7
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp1000+AC+H20.7+CH40.7+NH30.7+FT0.7+MeOH0.7+St0.7
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-imp500+AC+H20.7+CH40.7+NH30.7+FT0.7+MeOH0.7+St0.7
  # additional scenario: no hydrogen network
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-noH2network
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-noH2network-imp
  # additional scenario: no wasteheat
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-nowasteheat
  - Co2L0-2190SEG-T-H-B-I-S-A-onwind+p0.5-nowasteheat-imp
  planning_horizons:
  - 2050

enable:
  retrieve: true
  retrieve_databundle: false
  retrieve_sector_databundle: false
  retrieve_cutout: false

atlite:
  nprocesses: 12

electricity:
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc]
  conventional_carriers: []
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]

  estimate_renewable_capacities:
    enable: false

renewable:
  solar:
    capacity_per_sqkm: 5.1
  # onwind:
  #   capacity_per_sqkm: 1.5
  #   corine:
  #     # exclude forest
  #     grid_codes: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 26, 27, 28, 29, 31, 32]

lines:
  max_extension: 15000
  dynamic_line_rating:
    activate: true
    correction_factor: 0.95
    max_voltage_difference: 45.
    max_line_rating: 1.3

links:
  max_extension: 15000

biomass:
  year: 2050

sector:
  cluster_heat_buses: true
  co2_vent: true
  electricity_distribution_grid_cost_factor: 1.5
  land_transport_fuel_cell_share:
    2050: 0.
  land_transport_electric_share:
    2050: 1.
  land_transport_ice_share:
    2050: 0.
  shipping_endogenous:
    enable: false
    fuels:
    # - oil
    # - LNG
    - ammonia
    - methanol
    # - LH2
  endogenous_steel: true
  relocation_steel: true
  flexibility_steel: true
  endogenous_hvc: false
  solar_thermal: false
  hydrogen_turbine: false
  hydrogen_fuel_cell: true
  ammonia: true
  # https://github.com/euronion/trace/blob/main/data/efficiencies.csv
  transmission_efficiency:
    DC:
      efficiency_static: 0.98
      efficiency_per_1000km: 0.97
    H2 pipeline:
      efficiency_per_1000km: 1 # 0.979
      compression_per_1000km: 0.019
    gas pipeline:
      efficiency_per_1000km: 1 #0.977
      compression_per_1000km: 0.01
  gas_network: true
  H2_retrofit: false
  biomass_boiler: true
  biosng: false
  electrobiofuels: false
  biomass_to_liquid: false
  biomass_to_liquid_cc: false
  biomass_to_methanol: false
  biomass_to_methanol_cc: false
  biomass_upgrading_cc: true
  methanol_reforming: false
  methanol_reforming_cc: false
  methanol_to_kerosene: true
  methanol_to_power:
    ccgt: false
    ccgt_cc: false
    ocgt: false
    allam: false
  use_fischer_tropsch_waste_heat: true
  use_methanolisation_waste_heat: true
  use_methanation_waste_heat: true
  use_fuel_cell_waste_heat: true
  use_electrolysis_waste_heat: true
  use_haber_bosch_waste_heat: true
  min_part_load_fischer_tropsch: 0.7
  min_part_load_methanolisation: 0.3
  min_part_load_methanation: 0.3
  import:
    capacity_boost: 2.5
    limit: false # bool or number in TWh
    limit_sense: "=="
    options:
    - pipeline-h2
    - shipping-lh2
    - shipping-lch4
    - shipping-lnh3
    - shipping-ftfuel
    - shipping-meoh
    - shipping-steel
    - hvdc-to-elec
    p_nom_max:
      pipeline-h2: 50700 # EHB 3 parallel 48" pipelines
    endogenous_hvdc_import:
      enable: true
      exporters:
      - DZ
      - EG
      - KZ
      - LY
      - MA
      - SA
      - TN
      - TR
      - UA
      extra_connections: []
      xlinks:
        MA:
        # Plymouth
        - x: -4.14
          y: 50.39
          length: 3800
        # Cork
        - x: -8.52
          y: 51.92
          length: 4000
        # Brest
        - x: -4.49
          y: 48.43
          length: 3200
        # Vigo
        - x: -8.70
          y: 42.31
          length: 1800
        DZ:
        # Barcelona
        - x: 2.37
          y: 41.57
          length: 1300
        # Genoa
        - x: 8.93
          y: 44.41
          length: 1800
        # Marseille
        - x: 5.30
          y: 43.38
          length: 1400
        TN:
        # Genoa
        - x: 8.93
          y: 44.41
          length: 1500
        # Marseille
        - x: 5.30
          y: 43.38
          length: 1500
        LY:
        # Venice
        - x: 12.39
          y: 45.56
          length: 2500
        EG:
        # Venice
        - x: 12.39
          y: 45.56
          length: 2500
      efficiency_static: 0.98
      efficiency_per_1000km: 0.97 # p.u./km
      length_factor: 1.25
      distance_threshold: 0.05 # quantile
      p_nom_max: 25000 # MW
      share_of_p_nom_max_available: 0.25

industry:
  HVC_primary_fraction: 0.45
  HVC_mechanical_recycling_fraction: 0.3
  HVC_chemical_recycling_fraction: 0.15

solving:
  options:
    transmission_losses: 2
    linearized_unit_commitment: false
  
  solver:
    threads: 4
  
  solver_options:
    gurobi-default:
      BarConvTol: 1.e-5

  mem: 126000
  walltime: "90:00:00"