# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "test"
  shared_resources: false

remote:
  ssh: "zecm"
  path: "scratch/projects/import-benefits"

scenario:
  simpl:
  - ''
  ll:
  - v1.5
  clusters:
  - 128
  opts:
  - ''
  sector_opts:
  - Co2L0-2190H-T-H-B-I-S-A
  - Co2L0-2190H-T-H-B-I-S-A-imp
  # - Co2L0-2190H-T-H-B-I-S-A-imp+AC
  # - Co2L0-2190H-T-H-B-I-S-A-imp+H2
  # - Co2L0-2190H-T-H-B-I-S-A-imp+CH4
  # - Co2L0-2190H-T-H-B-I-S-A-imp+NH3
  # - Co2L0-2190H-T-H-B-I-S-A-imp+FT
  # - Co2L0-2190H-T-H-B-I-S-A-imp+MeOH
  # - Co2L0-2190H-T-H-B-I-S-A-imp+St # products
  # - Co2L0-2190H-T-H-B-I-S-A-imp+H2+CH4+NH3+FT+MeOH  # molecules
  # - Co2L0-2190H-T-H-B-I-S-A-imp+CH4+NH3-FT+MeOH  # hydrogen derivatives
  # - Co2L0-2190H-T-H-B-I-S-A-imp+MeOH+FT # liquid carbonaceous fuels
  # - Co2L0-2190H-T-H-B-I-S-A-imp+CH4+FT+MeOH  # carbonaceous fuels
  # - Co2L0-2190H-T-H-B-I-S-A-imp500+AC
  # - Co2L0-2190H-T-H-B-I-S-A-imp500+H2
  # - Co2L0-2190H-T-H-B-I-S-A-imp500+CH4
  # - Co2L0-2190H-T-H-B-I-S-A-imp500+NH3
  # - Co2L0-2190H-T-H-B-I-S-A-imp500+FT
  # - Co2L0-2190H-T-H-B-I-S-A-imp500+MeOH
  # - Co2L0-2190H-T-H-B-I-S-A-imp500+MeOH+FT
  # - Co2L0-2190H-T-H-B-I-S-A-imp1000+AC
  # - Co2L0-2190H-T-H-B-I-S-A-imp1000+H2
  # - Co2L0-2190H-T-H-B-I-S-A-imp1000+CH4
  # - Co2L0-2190H-T-H-B-I-S-A-imp1000+NH3
  # - Co2L0-2190H-T-H-B-I-S-A-imp1000+FT
  # - Co2L0-2190H-T-H-B-I-S-A-imp1000+MeOH
  # - Co2L0-2190H-T-H-B-I-S-A-imp1000+MeOH+FT
  # - Co2L0-2190H-T-H-B-I-S-A-imp1500+CH4
  # - Co2L0-2190H-T-H-B-I-S-A-imp1500+NH3
  # - Co2L0-2190H-T-H-B-I-S-A-imp1500+FT
  # - Co2L0-2190H-T-H-B-I-S-A-imp1500+MeOH
  # - Co2L0-2190H-T-H-B-I-S-A-imp1500+MeOH+FT
  # - Co2L0-2190H-T-H-B-I-S-A-imp1000+H2+CH4+NH3+FT+MeOH
  # - Co2L0-2190H-T-H-B-I-S-A-imp2000+AC
  # - Co2L0-2190H-T-H-B-I-S-A-imp2000+H2
  # - Co2L0-2190H-T-H-B-I-S-A-imp2000+CH4
  # - Co2L0-2190H-T-H-B-I-S-A-imp2000+NH3
  # - Co2L0-2190H-T-H-B-I-S-A-imp2000+H2+CH4+NH3+FT+MeOH
  # - Co2L0-2190H-T-H-B-I-S-A-imp2000+FT
  # - Co2L0-2190H-T-H-B-I-S-A-imp2000+MeOH
  # - Co2L0-2190H-T-H-B-I-S-A-imp2000+MeOH+FT
  # - Co2L0-2190H-T-H-B-I-S-A-imp3000+AC
  # - Co2L0-2190H-T-H-B-I-S-A-imp3000+H2
  # - Co2L0-2190H-T-H-B-I-S-A-imp3000+H2+CH4+NH3+FT+MeOH
  # - Co2L0-2190H-T-H-B-I-S-A-imp3000+MeOH+FT
  # - Co2L0-2190H-T-H-B-I-S-A-imp4000+AC
  # - Co2L0-2190H-T-H-B-I-S-A-imp4000+H2
  # - Co2L0-2190H-T-H-B-I-S-A-imp4000+H2+CH4+NH3+FT+MeOH
  # - Co2L0-2190H-T-H-B-I-S-A-imp5000+AC
  # - Co2L0-2190H-T-H-B-I-S-A-imp5000+H2
  # - Co2L0-2190H-T-H-B-I-S-A-imp5000+H2+CH4+NH3+FT+MeOH
  # - Co2L0-2190H-T-H-B-I-S-A-imp6000+H2
  # - Co2L0-2190H-T-H-B-I-S-A-imp6000+AC
  # - Co2L0-2190H-T-H-B-I-S-A-imp7000+H2
  # - Co2L0-2190H-T-H-B-I-S-A-imp10000
  # - Co2L0-2190H-T-H-B-I-S-A-imp9000
  # - Co2L0-2190H-T-H-B-I-S-A-imp8000
  # - Co2L0-2190H-T-H-B-I-S-A-imp7000
  # - Co2L0-2190H-T-H-B-I-S-A-imp6000
  # - Co2L0-2190H-T-H-B-I-S-A-imp5000
  # - Co2L0-2190H-T-H-B-I-S-A-imp4000
  # - Co2L0-2190H-T-H-B-I-S-A-imp3000
  # - Co2L0-2190H-T-H-B-I-S-A-imp2000
  # - Co2L0-2190H-T-H-B-I-S-A-imp1000
  # - Co2L0-2190H-T-H-B-I-S-A-imp500
  # - Co2L0-2190H-T-H-B-I-S-A-imp10000+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  # - Co2L0-2190H-T-H-B-I-S-A-imp8000+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  # - Co2L0-2190H-T-H-B-I-S-A-imp6000+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  # - Co2L0-2190H-T-H-B-I-S-A-imp4000+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  # - Co2L0-2190H-T-H-B-I-S-A-imp2000+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  # - Co2L0-2190H-T-H-B-I-S-A-imp1000+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  # - Co2L0-2190H-T-H-B-I-S-A-imp500+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  # - Co2L0-2190H-T-H-B-I-S-A-imp10000+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  # - Co2L0-2190H-T-H-B-I-S-A-imp8000+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  # - Co2L0-2190H-T-H-B-I-S-A-imp6000+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  # - Co2L0-2190H-T-H-B-I-S-A-imp4000+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  # - Co2L0-2190H-T-H-B-I-S-A-imp2000+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  # - Co2L0-2190H-T-H-B-I-S-A-imp1000+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  # - Co2L0-2190H-T-H-B-I-S-A-imp500+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  # - Co2L0-2190H-T-H-B-I-S-A-imp+AC0.9+H20.9+CH40.9+NH30.9+FT0.9+MeOH0.9+St0.9
  # - Co2L0-2190H-T-H-B-I-S-A-imp+AC0.8+H20.8+CH40.8+NH30.8+FT0.8+MeOH0.8+St0.8
  # - Co2L0-2190H-T-H-B-I-S-A-imp+AC1.1+H21.1+CH41.1+NH31.1+FT1.1+MeOH1.1+St1.1
  # - Co2L0-2190H-T-H-B-I-S-A-imp+AC1.2+H21.2+CH41.2+NH31.2+FT1.2+MeOH1.2+St1.2
  planning_horizons:
  - 2050

enable:
  retrieve_databundle: false
  retrieve_sector_databundle: false
  retrieve_cutout: false

atlite:
  nprocesses: 7

electricity:
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc]
  conventional_carriers: []
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]

  estimate_renewable_capacities:
    enable: false

renewable:
  solar:
    capacity_per_sqkm: 5.1

lines:
  max_extension: 15000

sector:
  land_transport_fuel_cell_share:
    2050: 0.
  land_transport_electric_share:
    2050: 1.
  land_transport_ice_share:
    2050: 0.
  shipping_endogenous:
    enable: true
    fuels:
    - oil
    - LNG
    - ammonia
    - methanol
    # - LH2
  endogenous_steel: true
  endogenous_hvc: true
  solar_thermal: false
  allam_cycle_gas: true
  hydrogen_turbine: true
  ammonia: true
  HVC_primary_fraction: 0.45
  HVC_mechanical_recycling_fraction: 0.3
  HVC_chemical_recycling_fraction: 0.15
  use_electrolysis_waste_heat: true
  # https://github.com/euronion/trace/blob/main/data/efficiencies.csv
  transmission_efficiency:
    DC:
      efficiency_static: 0.98
      efficiency_per_1000km: 0.977
    H2 pipeline:
      efficiency_per_1000km: 1 # 0.979
      compression_per_1000km: 0.019
    gas pipeline:
      efficiency_per_1000km: 1 #0.977
      compression_per_1000km: 0.01
  gas_network: true
  H2_retrofit: false
  biomass_to_liquid: true
  biomass_to_methanol: true
  methanol_reforming: true
  methanol_to_kerosene: true
  methanol_to_power:
    ccgt: true
    ccgt_cc: true
    ocgt: true
    allam: true
  import:
    capacity_boost: 2
    limit: false # bool or number in TWh
    limit_sense: "=="
    options:
    - pipeline-h2
    - shipping-lh2
    - shipping-lch4
    - shipping-lnh3
    - shipping-ftfuel
    - shipping-meoh
    - shipping-steel
    - hvdc-to-elec
    endogenous_hvdc_import:
      enable: true
      exporters:
      - CN-West
      - DZ
      - EG
      - KZ
      - LY
      - MA
      - SA
      - TN
      - TR
      - UA
      extra_connections:
      - MA-DZ
      - DZ-LY
      - DZ-TN
      - TN-LY
      - LY-EG
      - EG-SA
      xlinks:
        MA:
        # Plymouth
        - x: -4.14
          y: 50.39
          length: 3800
        # Cork
        - x: -8.52
          y: 51.92
          length: 4000
        # Brest
        - x: -4.49
          y: 48.43
          length: 3200
        # Vigo
        - x: -8.70
          y: 42.31
          length: 1800
        DZ:
        # Barcelona
        - x: 2.37
          y: 41.57
          length: 1300
        # Genoa
        - x: 8.93
          y: 44.41
          length: 1800
        # Marseille
        - x: 5.30
          y: 43.38
          length: 1400
        TN:
        # Genoa
        - x: 8.93
          y: 44.41
          length: 1500
        # Marseille
        - x: 5.30
          y: 43.38
          length: 1500
        LY:
        # Venice
        - x: 12.39
          y: 45.56
          length: 2500
        EG:
        # Venice
        - x: 12.39
          y: 45.56
          length: 2500
      hvdc_losses: 3.e-5 # p.u./km
      length_factor: 1.25
      distance_threshold: 0.05 # quantile

industry:
  HVC_primary_fraction: 0.45
  HVC_mechanical_recycling_fraction: 0.3
  HVC_chemical_recycling_fraction: 0.15

solving:
  options:
    transmission_losses: 2

  solver_options:
    gurobi-default:
      BarConvTol: 1.e-5

  mem: 125000
